"use client"

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react'

type Language = 'zh' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string | string[]
  isDetecting: boolean
}

const translations = {
  zh: {
    // Navigation
    'nav.upload': '上传文件',
    'nav.dashboard': '我的面板',
    'nav.pricing': '升级账户',
    'nav.login': '登录',
    'nav.register': '免费注册',
    'nav.version': 'v0版本',
    
    // Hero Section
    'hero.title': '病毒式文件加密分享平台',
    'hero.subtitle': '安全分享文件，邀请好友获得奖励，打造最安全的文件分享网络',
    'hero.cta': '立即开始',
    'hero.demo': '观看演示',
    
    // Features
    'features.title': '为什么选择 SecureFiles？',
    'features.subtitle': '我们提供最先进的安全技术和用户友好的体验',
    'feature.security.title': '军事级加密',
    'feature.security.description': '使用AES-256加密算法，确保您的文件绝对安全',
    'feature.sharing.title': '智能分享',
    'feature.sharing.description': '一键生成安全链接，支持密码保护和过期时间设置',
    'feature.rewards.title': '病毒式传播',
    'feature.rewards.description': '邀请好友使用，获得存储空间和高级功能奖励',
    'feature.analytics.title': '详细分析',
    'feature.analytics.description': '实时查看文件访问统计和用户行为分析',
    
    // Social Proof
    'social.title': '用户信赖我们',
    'social.subtitle': '加入数万用户的行列，体验最安全的文件分享',
    'social.stats.users': '用户',
    'social.stats.files': '文件',
    'social.stats.security': '安全等级',
    
    // Pricing - 统一定价策略
    'pricing.title': '选择适合您的计划',
    'pricing.subtitle': '从免费开始，按需升级',
    'pricing.free.title': '免费版',
    'pricing.free.price': '¥0',
    'pricing.free.period': '/月',
    'pricing.free.storage': '50MB 文件限制',
    'pricing.free.files': '基础加密/压缩',
    'pricing.free.sharing': '网页版使用',
    'pricing.free.support': '社区支持',
    'pricing.pro.title': '专业版',
    'pricing.pro.price': '¥75',
    'pricing.pro.period': '/月',
    'pricing.pro.storage': '2GB 文件限制',
    'pricing.pro.files': '客户端应用+批量处理',
    'pricing.pro.sharing': '高级加密算法',
    'pricing.pro.analytics': '智能压缩',
    'pricing.pro.support': '优先技术支持',
    'pricing.enterprise.title': '企业版',
    'pricing.enterprise.price': '¥225',
    'pricing.enterprise.period': '/月',
    'pricing.enterprise.storage': '无文件大小限制',
    'pricing.enterprise.files': '团队协作+API',
    'pricing.enterprise.sharing': '军用级加密',
    'pricing.enterprise.analytics': '多级压缩',
    'pricing.enterprise.support': '24/7 专属支持',
    'pricing.cta.free': '开始使用',
    'pricing.cta.pro': '升级专业版',
    'pricing.cta.enterprise': '联系销售',
    
    // Client App Pricing
    'pricing.client.title': '客户端应用定价',
    'pricing.client.subtitle': '处理大文件，享受更强大的功能',
    'pricing.client.free.title': '免费版',
    'pricing.client.free.price': '¥0',
    'pricing.client.free.period': '永久',
    'pricing.client.free.storage': '50MB 文件限制',
    'pricing.client.free.files': '基础加密算法',
    'pricing.client.free.sharing': '标准压缩',
    'pricing.client.free.support': '网页版使用',
    'pricing.client.pro.title': '专业版',
    'pricing.client.pro.price': '¥75',
    'pricing.client.pro.period': '/月',
    'pricing.client.pro.storage': '2GB 文件限制',
    'pricing.client.pro.files': '高级加密算法',
    'pricing.client.pro.sharing': '智能压缩',
    'pricing.client.pro.analytics': '客户端应用',
    'pricing.client.pro.support': '批量处理',
    'pricing.client.enterprise.title': '企业版',
    'pricing.client.enterprise.price': '¥225',
    'pricing.client.enterprise.period': '/月',
    'pricing.client.enterprise.storage': '无文件大小限制',
    'pricing.client.enterprise.files': '军用级加密',
    'pricing.client.enterprise.sharing': '多级压缩',
    'pricing.client.enterprise.analytics': '团队协作',
    'pricing.client.enterprise.support': 'API访问',
    'pricing.client.cta.free': '免费下载',
    'pricing.client.cta.pro': '立即购买',
    'pricing.client.cta.enterprise': '联系销售',
    
    // Upload Page
    'upload.title': '上传文件',
    'upload.subtitle': '选择文件开始安全分享',
    'upload.dragDrop': '拖拽文件到此处，或点击选择文件',
    'upload.selectFiles': '选择文件',
    'upload.maxSize': '最大文件大小: 100MB',
    'upload.supportedFormats': '支持格式: PDF, DOC, XLS, PPT, JPG, PNG, MP4',
    'upload.uploading': '上传中...',
    'upload.success': '上传成功！',
    'upload.error': '上传失败，请重试',
    'upload.shareLink': '分享链接',
    'upload.copyLink': '复制链接',
    'upload.setPassword': '设置密码',
    'upload.setExpiry': '设置过期时间',
    
    // Dashboard
    'dashboard.title': '我的面板',
    'dashboard.subtitle': '管理您的文件和分享',
    'dashboard.stats.files': '文件总数',
    'dashboard.stats.shares': '分享次数',
    'dashboard.stats.storage': '已用存储',
    'dashboard.recentFiles': '最近文件',
    'dashboard.recentShares': '最近分享',
    'dashboard.noFiles': '暂无文件',
    'dashboard.uploadFirst': '上传您的第一个文件',
    
    // Encryption Page
    'encrypt.title': '文件加密工具',
    'encrypt.subtitle': '安全加密您的文件，生成密码用于解密。请妥善保管密码！',
    'encrypt.selectFile': '选择文件',
    'encrypt.algorithm': '加密算法',
    'encrypt.password': '解密密码',
    'encrypt.generate': '生成',
    'encrypt.showPassword': '显示密码',
    'encrypt.keepOriginal': '保留原始文件',
    'encrypt.encryptFile': '加密文件',
    'encrypt.encrypting': '加密中...',
    'encrypt.success': '加密成功',
    'encrypt.error': '加密失败',
    'encrypt.downloadEncrypted': '下载加密文件',
    'encrypt.copyPassword': '复制密码',
    'encrypt.passwordWarning': '请务必保存此密码！没有密码将无法解密文件。',
    'encrypt.howToUse': '如何使用',
    'encrypt.step1': '保存密码到安全的地方',
    'encrypt.step2': '下载加密文件',
    'encrypt.step3': '使用我们的解密工具恢复原始文件',
    'encrypt.newFile': '加密新文件',
    'encrypt.noResults': '选择文件并加密后，结果将显示在这里',
    'encrypt.securityNotice': '安全提醒',
    'encrypt.security1': '密码永远不会存储在我们的服务器上',
    'encrypt.security2': '加密在您的浏览器中本地进行',
    'encrypt.security3': '请妥善保管密码，丢失后将无法恢复文件',
    'encrypt.security4': '建议使用强密码并定期更换',
    
    // Decryption Page
    'decrypt.title': '文件解密工具',
    'decrypt.subtitle': '使用密码解密您的文件，恢复原始内容',
    'decrypt.selectFile': '选择加密文件',
    'decrypt.password': '解密密码',
    'decrypt.decryptFile': '解密文件',
    'decrypt.decrypting': '解密中...',
    'decrypt.success': '解密成功',
    'decrypt.error': '解密失败',
    'decrypt.originalFileName': '原始文件名',
    'decrypt.fileSize': '文件大小',
    'decrypt.downloadOriginal': '下载原始文件',
    'decrypt.newFile': '解密新文件',
    'decrypt.noResults': '上传加密文件并输入密码后，结果将显示在这里',
    'decrypt.instructions': '使用说明',
    'decrypt.instruction1': '上传之前加密的文件（.encrypted格式）',
    'decrypt.instruction2': '输入创建加密文件时使用的密码',
    'decrypt.instruction3': '点击解密按钮开始解密过程',
    'decrypt.instruction4': '下载解密后的原始文件',
    'decrypt.troubleshooting': '常见问题',
    'decrypt.faq1.question': '解密失败怎么办？',
    'decrypt.faq1.answer': '请检查密码是否正确，确保文件没有损坏',
    'decrypt.faq2.question': '忘记密码了？',
    'decrypt.faq2.answer': '很抱歉，由于加密特性，我们无法恢复丢失的密码',
    'decrypt.faq3.question': '支持哪些文件格式？',
    'decrypt.faq3.answer': '支持所有文件格式，包括文档、图片、视频等',
    
    // Cloud Storage Page
    'cloud.title': '云端文件存储',
    'cloud.subtitle': '安全存储文件，生成分享链接，随时随地访问',
    'cloud.uploadFile': '上传文件',
    'cloud.selectFile': '选择文件',
    'cloud.encryptionAlgorithm': '加密算法',
    'cloud.expiryTime': '过期时间',
    'cloud.maxDownloads': '最大下载次数',
    'cloud.backupOriginal': '备份原始文件',
    'cloud.uploadToCloud': '上传到云端',
    'cloud.uploading': '上传中...',
    'cloud.success': '上传成功',
    'cloud.error': '上传失败',
    'cloud.storageInfo': '存储信息',
    'cloud.used': '已使用',
    'cloud.total': '总容量',
    'cloud.usedPercent': '已使用',
    'cloud.activeFiles': '活跃文件',
    'cloud.totalDownloads': '总下载次数',
    'cloud.storedFiles': '已存储文件',
    'cloud.noFiles': '还没有上传任何文件到云端',
    'cloud.downloads': '下载',
    'cloud.daysLeft': '天剩余',
    'cloud.expired': '已过期',
    'cloud.backedUp': '已备份',
    'cloud.copyLink': '复制链接',
    'cloud.openLink': '打开链接',
    'cloud.deleteFile': '删除文件',
    'cloud.militaryEncryption': '军事级加密',
    'cloud.militaryDescription': '所有文件都经过AES-256加密',
    'cloud.instantSharing': '即时分享',
    'cloud.instantDescription': '一键生成安全的分享链接',
    'cloud.autoExpiry': '自动过期',
    'cloud.autoDescription': '设置文件自动过期时间',
    
    // Share Page
    'share.title': '共享文件',
    'share.subtitle': '安全下载共享的文件',
    'share.loading': '加载共享文件...',
    'share.notFound': '文件未找到',
    'share.notFoundDesc': '此分享链接无效或文件已被删除',
    'share.available': '可用',
    'share.expired': '已过期',
    'share.passwordProtected': '需要密码',
    'share.fileSize': '文件大小',
    'share.uploaded': '上传时间',
    'share.downloads': '下载次数',
    'share.timeLeft': '剩余时间',
    'share.days': '天',
    'share.accessPassword': '访问密码',
    'share.enterPassword': '输入访问密码',
    'share.downloadFile': '下载文件',
    'share.downloading': '下载中...',
    'share.fileExpired': '文件已过期',
    'share.fileExpiredDesc': '此文件的分享链接已过期，无法下载',
    'share.downloadLimit': '下载次数已达上限',
    'share.downloadLimitDesc': '此文件已达到最大下载次数限制',
    'share.securityNotice': '安全提醒',
    'share.security1': '文件经过军事级加密保护',
    'share.security2': '下载链接具有时效性',
    'share.security3': '请勿分享密码给不信任的人',
    'share.security4': '下载完成后请及时删除本地文件',
    
    // Viral Demo
    'viral.title': '病毒式分享机制演示',
    'viral.subtitle': '每次分享都能获得实际奖励，邀请越多，特权越多',
    'viral.shareCard.title': '病毒式分享卡片',
    'viral.shareCard.received': '您收到一个安全文件！',
    'viral.shareCard.filename': '财务报告_Q3_加密文件.pdf',
    'viral.shareCard.expires': '有效期剩余：23小时',
    'viral.shareCard.sender': '发送方：mike@company.com',
    'viral.shareCard.decrypt': '解密文件并分享',
    'viral.rewards.title': '分享奖励进度',
    'viral.rewards.completed': '已完成分享次数',
    'viral.rewards.encryption': '增强加密解锁',
    'viral.rewards.encryption.desc': 'AES-256加密算法',
    'viral.rewards.premium': '7天高级体验',
    'viral.rewards.premium.desc': '1GB文件 + 自毁链接',
    'viral.rewards.permanent': '永久基础特权',
    'viral.rewards.permanent.desc': '无限制分享次数',
    'viral.rewards.earned': '已获得',
    'viral.rewards.congrats': '🎉 恭喜获得奖励！',
    
    // Upgrade Modal
    'upgrade.title': '升级您的账户',
    'upgrade.limit.title': '文件超过50MB限制！',
    'upgrade.limit.description': '升级账号即可解锁1GB超大文件支持，或邀请3位好友免费体验7天',
    'upgrade.free.title': '免费获取高级功能',
    'upgrade.free.invite1': '邀请1人',
    'upgrade.free.invite1.desc': '解锁增强加密',
    'upgrade.free.invite3': '邀请3人',
    'upgrade.free.invite3.desc': '获得7天高级体验',
    'upgrade.free.invite5': '邀请5人',
    'upgrade.free.invite5.desc': '永久基础特权',
    'upgrade.free.cta': '开始邀请好友',
    'upgrade.pro.title': '基础付费',
    'upgrade.pro.price': '$5',
    'upgrade.pro.period': '/月',
    'upgrade.pro.features': ['文件大小 ≤1GB', '存储时间 1年', 'AES-256加密', '自毁链接功能', '无限制分享'],
    'upgrade.enterprise.title': '高级付费',
    'upgrade.enterprise.price': '$15',
    'upgrade.enterprise.period': '/月',
    'upgrade.enterprise.features': ['文件大小 ≤10GB', '永久存储', 'XChaCha20加密', '追踪墙+时间锁', 'API接入', '优先客服支持'],
    'upgrade.popular': '最受欢迎',
    'upgrade.cta': '立即升级',

    
    // Pricing Table
    'pricing.table.selfDestruct': '自毁链接',
    'pricing.table.tracking': '访问追踪',
    'pricing.table.api': 'API接入',
    'pricing.table.support': '客服支持',
    'pricing.table.basic': '基础',
    'pricing.table.standard': '标准',
    'pricing.table.premium': '高级',
    'pricing.table.unlimited': '无限制',
    'pricing.table.7days': '7天',
    'pricing.table.1year': '1年',
    'pricing.table.permanent': '永久',
    'pricing.table.3perWeek': '3次/周',
    
    // FAQ Section
    'faq.title': '常见问题',
    'faq.invite.question': '如何通过邀请获得免费功能？',
    'faq.invite.answer': '分享您的专属邀请链接，好友注册成功后您将自动获得对应奖励。邀请1人解锁增强加密，邀请3人获得7天高级体验，邀请5人获得永久基础特权。',
    'faq.cancel.question': '付费方案可以随时取消吗？',
    'faq.cancel.answer': '是的，您可以随时取消订阅。取消后您仍可使用至当前计费周期结束，之后将自动降级为免费版本。',
    'faq.security.question': '文件安全性如何保证？',
    'faq.security.answer': '我们采用端到端加密，文件在上传前就在您的设备上加密。服务器只存储加密后的数据，即使是我们也无法访问您的原始文件内容。',
    'faq.payment.question': '支持哪些支付方式？',
    'faq.payment.answer': '支持信用卡、PayPal、支付宝、微信支付等多种支付方式。所有支付都通过安全的第三方支付平台处理。',
    
    // Usage Statistics
    'stats.secureFiles': '安全加密文件',
    'stats.savedSpace': '节省存储空间',
    'stats.securityBenefits': '安全收益统计',
    'stats.blockedSnooping': '阻止了{count}次潜在窥探',
    'stats.protectedFiles': '保护了{count}份重要文件',
    'stats.gainedTrust': '获得了{count}位好友信任',
    
    // Common
    'common.switchLanguage': '切换语言',
    'common.chinese': '中文',
    'common.english': 'English',
    'common.loading': '加载中...',
    'common.error': '出错了',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.view': '查看',
    'common.download': '下载',
    'common.share': '分享',
    'common.copy': '复制',
    'common.close': '关闭',
  },
  en: {
    // Navigation
    'nav.upload': 'Upload',
    'nav.dashboard': 'Dashboard',
    'nav.pricing': 'Pricing',
    'nav.login': 'Login',
    'nav.register': 'Sign Up',
    'nav.version': 'v0',
    
    // Hero Section
    'hero.title': 'Viral File Encryption & Sharing Platform',
    'hero.subtitle': 'Securely share files, invite friends for rewards, build the safest file sharing network',
    'hero.cta': 'Get Started',
    'hero.demo': 'Watch Demo',
    
    // Features
    'features.title': 'Why Choose SecureFiles?',
    'features.subtitle': 'We provide the most advanced security technology and user-friendly experience',
    'feature.security.title': 'Military Grade Encryption',
    'feature.security.description': 'Using AES-256 encryption algorithm to ensure your files are absolutely secure',
    'feature.sharing.title': 'Smart Sharing',
    'feature.sharing.description': 'One-click secure link generation with password protection and expiry time settings',
    'feature.rewards.title': 'Viral Spread',
    'feature.rewards.description': 'Invite friends to use and get storage space and premium feature rewards',
    'feature.analytics.title': 'Detailed Analytics',
    'feature.analytics.description': 'Real-time file access statistics and user behavior analysis',
    
    // Social Proof
    'social.title': 'Users Trust Us',
    'social.subtitle': 'Join tens of thousands of users to experience the safest file sharing',
    'social.stats.users': 'Users',
    'social.stats.files': 'Files',
    'social.stats.security': 'Security Level',
    
    // Pricing - Unified Pricing Strategy
    'pricing.title': 'Choose Your Plan',
    'pricing.subtitle': 'Start free, upgrade as needed',
    'pricing.free.title': 'Free',
    'pricing.free.price': '$0',
    'pricing.free.period': '/month',
    'pricing.free.storage': '50MB file limit',
    'pricing.free.files': 'Basic encryption/compression',
    'pricing.free.sharing': 'Web version access',
    'pricing.free.support': 'Community support',
    'pricing.pro.title': 'Pro',
    'pricing.pro.price': '$9.99',
    'pricing.pro.period': '/month',
    'pricing.pro.storage': '2GB file limit',
    'pricing.pro.files': 'Desktop client + batch processing',
    'pricing.pro.sharing': 'Advanced encryption algorithms',
    'pricing.pro.analytics': 'Smart compression',
    'pricing.pro.support': 'Priority support',
    'pricing.enterprise.title': 'Enterprise',
    'pricing.enterprise.price': '$29.99',
    'pricing.enterprise.period': '/month',
    'pricing.enterprise.storage': 'Unlimited file size',
    'pricing.enterprise.files': 'Team collaboration + API',
    'pricing.enterprise.sharing': 'Military-grade encryption',
    'pricing.enterprise.analytics': 'Multi-level compression',
    'pricing.enterprise.support': '24/7 dedicated support',
    'pricing.cta.free': 'Get Started',
    'pricing.cta.pro': 'Upgrade to Pro',
    'pricing.cta.enterprise': 'Contact Sales',
    
    // Client App Pricing
    'pricing.client.title': 'Desktop Client Pricing',
    'pricing.client.subtitle': 'Handle large files with powerful features',
    'pricing.client.free.title': 'Free',
    'pricing.client.free.price': '$0',
    'pricing.client.free.period': 'Forever',
    'pricing.client.free.storage': '50MB file limit',
    'pricing.client.free.files': 'Basic encryption algorithms',
    'pricing.client.free.sharing': 'Standard compression',
    'pricing.client.free.support': 'Web version access',
    'pricing.client.pro.title': 'Pro',
    'pricing.client.pro.price': '$9.99',
    'pricing.client.pro.period': '/month',
    'pricing.client.pro.storage': '2GB file limit',
    'pricing.client.pro.files': 'Advanced encryption algorithms',
    'pricing.client.pro.sharing': 'Smart compression',
    'pricing.client.pro.analytics': 'Desktop client app',
    'pricing.client.pro.support': 'Batch processing',
    'pricing.client.enterprise.title': 'Enterprise',
    'pricing.client.enterprise.price': '$29.99',
    'pricing.client.enterprise.period': '/month',
    'pricing.client.enterprise.storage': 'Unlimited file size',
    'pricing.client.enterprise.files': 'Military-grade encryption',
    'pricing.client.enterprise.sharing': 'Multi-level compression',
    'pricing.client.enterprise.analytics': 'Team collaboration',
    'pricing.client.enterprise.support': 'API access',
    'pricing.client.cta.free': 'Free Download',
    'pricing.client.cta.pro': 'Get Started',
    'pricing.client.cta.enterprise': 'Contact Sales',
    
    // Upload Page
    'upload.title': 'Upload File',
    'upload.subtitle': 'Select files to start secure sharing',
    'upload.dragDrop': 'Drag and drop files here, or click to select',
    'upload.selectFiles': 'Select Files',
    'upload.maxSize': 'Max file size: 100MB',
    'upload.supportedFormats': 'Supported formats: PDF, DOC, XLS, PPT, JPG, PNG, MP4',
    'upload.uploading': 'Uploading...',
    'upload.success': 'Upload successful!',
    'upload.error': 'Upload failed, please try again',
    'upload.shareLink': 'Share Link',
    'upload.copyLink': 'Copy Link',
    'upload.setPassword': 'Set Password',
    'upload.setExpiry': 'Set Expiry',
    
    // Dashboard
    'dashboard.title': 'My Dashboard',
    'dashboard.subtitle': 'Manage your files and shares',
    'dashboard.stats.files': 'Total Files',
    'dashboard.stats.shares': 'Total Shares',
    'dashboard.stats.storage': 'Storage Used',
    'dashboard.recentFiles': 'Recent Files',
    'dashboard.recentShares': 'Recent Shares',
    'dashboard.noFiles': 'No files yet',
    'dashboard.uploadFirst': 'Upload your first file',
    
    // Encryption Page
    'encrypt.title': 'File Encryption Tool',
    'encrypt.subtitle': 'Securely encrypt your files and generate a password for decryption. Keep your password safe!',
    'encrypt.selectFile': 'Select File',
    'encrypt.algorithm': 'Encryption Algorithm',
    'encrypt.password': 'Decryption Password',
    'encrypt.generate': 'Generate',
    'encrypt.showPassword': 'Show password',
    'encrypt.keepOriginal': 'Keep original file',
    'encrypt.encryptFile': 'Encrypt File',
    'encrypt.encrypting': 'Encrypting...',
    'encrypt.success': 'Encryption Successful',
    'encrypt.error': 'Encryption Failed',
    'encrypt.downloadEncrypted': 'Download Encrypted File',
    'encrypt.copyPassword': 'Copy Password',
    'encrypt.passwordWarning': 'Please save this password! You cannot decrypt the file without it.',
    'encrypt.howToUse': 'How to Use',
    'encrypt.step1': 'Save password to a secure location',
    'encrypt.step2': 'Download the encrypted file',
    'encrypt.step3': 'Use our decryption tool to recover the original file',
    'encrypt.newFile': 'Encrypt New File',
    'encrypt.noResults': 'Select a file and encrypt it to see results here',
    'encrypt.securityNotice': 'Security Notice',
    'encrypt.security1': 'Passwords are never stored on our servers',
    'encrypt.security2': 'Encryption is performed locally in your browser',
    'encrypt.security3': 'Keep your password safe, lost passwords cannot recover files',
    'encrypt.security4': 'Use strong passwords and change them regularly',
    
    // Decryption Page
    'decrypt.title': 'File Decryption Tool',
    'decrypt.subtitle': 'Decrypt your files using the password to recover original content',
    'decrypt.selectFile': 'Select Encrypted File',
    'decrypt.password': 'Decryption Password',
    'decrypt.decryptFile': 'Decrypt File',
    'decrypt.decrypting': 'Decrypting...',
    'decrypt.success': 'Decryption Successful',
    'decrypt.error': 'Decryption Failed',
    'decrypt.originalFileName': 'Original File Name',
    'decrypt.fileSize': 'File Size',
    'decrypt.downloadOriginal': 'Download Original File',
    'decrypt.newFile': 'Decrypt New File',
    'decrypt.noResults': 'Upload encrypted file and enter password to see results here',
    'decrypt.instructions': 'Instructions',
    'decrypt.instruction1': 'Upload your previously encrypted file (.encrypted format)',
    'decrypt.instruction2': 'Enter the password used when creating the encrypted file',
    'decrypt.instruction3': 'Click decrypt button to start the decryption process',
    'decrypt.instruction4': 'Download the decrypted original file',
    'decrypt.troubleshooting': 'Troubleshooting',
    'decrypt.faq1.question': 'What if decryption fails?',
    'decrypt.faq1.answer': 'Check if the password is correct and ensure the file is not corrupted',
    'decrypt.faq2.question': 'Forgot password?',
    'decrypt.faq2.answer': 'Sorry, due to encryption properties, we cannot recover lost passwords',
    'decrypt.faq3.question': 'What file formats are supported?',
    'decrypt.faq3.answer': 'All file formats are supported, including documents, images, videos, etc.',
    
    // Cloud Storage Page
    'cloud.title': 'Cloud File Storage',
    'cloud.subtitle': 'Securely store files, generate share links, access anywhere anytime',
    'cloud.uploadFile': 'Upload File',
    'cloud.selectFile': 'Select File',
    'cloud.encryptionAlgorithm': 'Encryption Algorithm',
    'cloud.expiryTime': 'Expiry Time',
    'cloud.maxDownloads': 'Maximum Downloads',
    'cloud.backupOriginal': 'Backup original file',
    'cloud.uploadToCloud': 'Upload to Cloud',
    'cloud.uploading': 'Uploading...',
    'cloud.success': 'Upload Successful',
    'cloud.error': 'Upload Failed',
    'cloud.storageInfo': 'Storage Info',
    'cloud.used': 'Used',
    'cloud.total': 'Total',
    'cloud.usedPercent': 'used',
    'cloud.activeFiles': 'Active Files',
    'cloud.totalDownloads': 'Total Downloads',
    'cloud.storedFiles': 'Stored Files',
    'cloud.noFiles': 'No files uploaded to cloud yet',
    'cloud.downloads': 'Downloads',
    'cloud.daysLeft': 'days left',
    'cloud.expired': 'Expired',
    'cloud.backedUp': 'Backed up',
    'cloud.copyLink': 'Copy Link',
    'cloud.openLink': 'Open Link',
    'cloud.deleteFile': 'Delete File',
    'cloud.militaryEncryption': 'Military Grade Encryption',
    'cloud.militaryDescription': 'All files encrypted with AES-256',
    'cloud.instantSharing': 'Instant Sharing',
    'cloud.instantDescription': 'Generate secure share links instantly',
    'cloud.autoExpiry': 'Auto Expiry',
    'cloud.autoDescription': 'Set automatic file expiry times',
    
    // Share Page
    'share.title': 'Shared File',
    'share.subtitle': 'Securely download the shared file',
    'share.loading': 'Loading shared file...',
    'share.notFound': 'File Not Found',
    'share.notFoundDesc': 'This share link is invalid or the file has been deleted',
    'share.available': 'Available',
    'share.expired': 'Expired',
    'share.passwordProtected': 'Password Protected',
    'share.fileSize': 'File Size',
    'share.uploaded': 'Uploaded',
    'share.downloads': 'Downloads',
    'share.timeLeft': 'Time Left',
    'share.days': 'days',
    'share.accessPassword': 'Access Password',
    'share.enterPassword': 'Enter access password',
    'share.downloadFile': 'Download File',
    'share.downloading': 'Downloading...',
    'share.fileExpired': 'File Expired',
    'share.fileExpiredDesc': 'This file\'s share link has expired and cannot be downloaded',
    'share.downloadLimit': 'Download Limit Reached',
    'share.downloadLimitDesc': 'This file has reached its maximum download limit',
    'share.securityNotice': 'Security Notice',
    'share.security1': 'Files are protected with military-grade encryption',
    'share.security2': 'Download links have time limits',
    'share.security3': 'Do not share passwords with untrusted parties',
    'share.security4': 'Delete local files after download',
    
    // Viral Demo
    'viral.title': 'Viral Sharing Mechanism Demo',
    'viral.subtitle': 'Every share earns real rewards, more invites mean more privileges',
    'viral.shareCard.title': 'Viral Share Card',
    'viral.shareCard.received': 'You received a secure file!',
    'viral.shareCard.filename': 'Financial Report_Q3_Encrypted.pdf',
    'viral.shareCard.expires': 'Expires in: 23 hours',
    'viral.shareCard.sender': 'From: mike@company.com',
    'viral.shareCard.decrypt': 'Decrypt & Share File',
    'viral.rewards.title': 'Share Rewards Progress',
    'viral.rewards.completed': 'Shares completed',
    'viral.rewards.encryption': 'Enhanced Encryption Unlocked',
    'viral.rewards.encryption.desc': 'AES-256 encryption algorithm',
    'viral.rewards.premium': '7-Day Premium Trial',
    'viral.rewards.premium.desc': '1GB files + Self-destruct links',
    'viral.rewards.permanent': 'Permanent Basic Privileges',
    'viral.rewards.permanent.desc': 'Unlimited sharing',
    'viral.rewards.earned': 'Earned',
    'viral.rewards.congrats': '🎉 Congratulations! Rewards earned!',
    
    // Upgrade Modal
    'upgrade.title': 'Upgrade Your Account',
    'upgrade.limit.title': 'File exceeds 50MB limit!',
    'upgrade.limit.description': 'Upgrade your account to unlock 1GB large file support, or invite 3 friends for a free 7-day trial',
    'upgrade.free.title': 'Get Premium Features Free',
    'upgrade.free.invite1': 'Invite 1 person',
    'upgrade.free.invite1.desc': 'Unlock enhanced encryption',
    'upgrade.free.invite3': 'Invite 3 people',
    'upgrade.free.invite3.desc': 'Get 7-day premium trial',
    'upgrade.free.invite5': 'Invite 5 people',
    'upgrade.free.invite5.desc': 'Permanent basic privileges',
    'upgrade.free.cta': 'Start Inviting Friends',
    'upgrade.pro.title': 'Pro Plan',
    'upgrade.pro.price': '$5',
    'upgrade.pro.period': '/month',
    'upgrade.pro.features': ['File size ≤1GB', 'Storage time 1 year', 'AES-256 encryption', 'Self-destruct links', 'Unlimited sharing'],
    'upgrade.enterprise.title': 'Enterprise Plan',
    'upgrade.enterprise.price': '$15',
    'upgrade.enterprise.period': '/month',
    'upgrade.enterprise.features': ['File size ≤10GB', 'Permanent storage', 'XChaCha20 encryption', 'Tracking wall + time lock', 'API access', 'Priority support'],
    'upgrade.popular': 'Most Popular',
    'upgrade.cta': 'Upgrade Now',


    
    // Pricing Table
    'pricing.table.selfDestruct': 'Self-destruct links',
    'pricing.table.tracking': 'Access tracking',
    'pricing.table.api': 'API access',
    'pricing.table.support': 'Customer support',
    'pricing.table.basic': 'Basic',
    'pricing.table.standard': 'Standard',
    'pricing.table.premium': 'Premium',
    'pricing.table.unlimited': 'Unlimited',
    'pricing.table.7days': '7 days',
    'pricing.table.1year': '1 year',
    'pricing.table.permanent': 'Permanent',
    'pricing.table.3perWeek': '3 times/week',
    
    // FAQ Section
    'faq.title': 'FAQ',
    'faq.invite.question': 'How can I get free features through invitation?',
    'faq.invite.answer': 'Share your exclusive invitation link, and you will automatically receive the corresponding reward when your friend registers successfully. Inviting 1 person unlocks enhanced encryption, inviting 3 people gets a 7-day premium trial, and inviting 5 people gets permanent basic privileges.',
    'faq.cancel.question': 'Can I cancel my paid plan at any time?',
    'faq.cancel.answer': 'Yes, you can cancel your subscription at any time. After cancellation, you can still use it until the end of the current billing cycle, after which it will automatically downgrade to the free version.',
    'faq.security.question': 'How is file security guaranteed?',
    'faq.security.answer': 'We use end-to-end encryption, files are encrypted on your device before uploading. The server only stores encrypted data, and even we cannot access your original file content.',
    'faq.payment.question': 'What payment methods are supported?',
    'faq.payment.answer': 'Supports credit cards, PayPal, Alipay, WeChat Pay, and other payment methods. All payments are processed through secure third-party payment platforms.',
    
    // Usage Statistics
    'stats.secureFiles': 'Securely encrypted files',
    'stats.savedSpace': 'Saved storage space',
    'stats.securityBenefits': 'Security benefits statistics',
    'stats.blockedSnooping': 'Blocked {count} potential snooping attempts',
    'stats.protectedFiles': 'Protected {count} important files',
    'stats.gainedTrust': 'Gained {count} friends\' trust',
    
    // Common
    'common.switchLanguage': 'Switch Language',
    'common.chinese': '中文',
    'common.english': 'English',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.download': 'Download',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.close': 'Close',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh')
  const [isDetecting, setIsDetecting] = useState(true)

  // Detect user's country and set initial language
  useEffect(() => {
    const detectUserLanguage = async () => {
      try {
        const response = await fetch('/api/detect-country')
        if (response.ok) {
          const data = await response.json()
          setLanguage(data.recommendedLanguage)
        }
      } catch (error) {
        console.error('Failed to detect user location:', error)
        // Keep default language (zh) if detection fails
      } finally {
        setIsDetecting(false)
      }
    }

    detectUserLanguage()
  }, [])

  const t = (key: string): string | string[] => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isDetecting }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 